// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package ideal

type Store struct {
	ID          int64
	Title       string
	Description string
	Userid      int64
}

type User struct {
	ID       int64
	Email    string
	Password string
}
